### ISSUE TITLE
Update readme to reflect correct entrypoint

### ISSUE THREAD

**Issue by k-rus** [timescale/timescaledb-docker#101]
TimescaleDB images propagate entry point from PostgreSQL, which developed over time. However, the instructions in the readme are not up-to-date and don't allow to run a container on an image without modifications.

**Comment by k-rus** [comment]
For example, authorization must be provided or trust when a container is created.

**Comment by svenklemm** [comment]
Required settings for the upstream container have changed but that seems unrelated to entrypoint.
