### ISSUE TITLE
"TimescaleDB Background Worker Scheduler" process is leaking memory

### ISSUE THREAD

**Issue by japsu** [timescale/timescaledb-docker#111]
Steps to reproduce:

1. Start a container from `timescaledev/timescale_prometheus_extra:latest-pg12`
2. Leave it running for a few weeks
3. Observe memory usage using eg. `htop`

Expected results:

* MEM% stays fairly constant

Actual results:

* MEM% grows from 0,2% to 80% (of 8GB)

Environment: https://github.com/japsu/kotiscale

**Comment by k-rus** [comment]
@japsu Thank you for reporting! Number of improvements were done in memory management for background workers in latest version. Can you try the docker image of 1.7.4, which is also the latest now?

**Comment by svenklemm** [comment]
Should be fixed in latest versions. https://github.com/timescale/timescaledb/pull/2184
