### ISSUE TITLE
configuration options with docker-compose

### ISSUE THREAD

**Issue by bonesoul** [timescale/timescaledb-docker#117]
Hey there,
In my testing & CI environment i'm using the the docker image and to get my tests run fast, i want to set fsync config option to false. How can I supply the parameter on docker image?

With vanilla postgres docker image, it's possible with;
https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/27295/diffs

**Comment by svenklemm** [comment]
You can set configuration options the same way you would use them in vanilla postgres since we inherit from vanilla postgres.
