### ISSUE TITLE
How can i update to postgis 3?

### ISSUE THREAD

**Issue by zuohuaijun** [timescale/timescaledb-docker#118]

**Comment by zuohuaijun** [comment]
could not open extension control file "/usr/local/share/postgresql/extension/pgrouting.control": No such file or directory

**Comment by k-rus** [comment]
PostGIS 3 is not available in the image, so you will need to bring it into the image. Only 2.5.3 is in the image. https://hub.docker.com/r/timescale/timescaledb-ha has TimescaleDB with PostGIS 3.

The request to add support for PostGIS 3 is https://github.com/timescale/timescaledb-docker/issues/96
I will close this issue in favour of #96.
