### ISSUE TITLE
How do I add pldbgapi to timescaledb-docker?

### ISSUE THREAD

**Issue by jflambert** [timescale/timescaledb-docker#119]
I'm currently using `timescale/timescaledb-postgis:1.7.4-pg12` in various forms (docker-compose, kubernetes) and I would like to be able to run `CREATE EXTENSION pldbgapi` once timescaledb is running.

I understand we would need to add the debian package `postgresql-12-pldebugger` or [build it from source](https://git.postgresql.org/gitweb/?p=pldebugger.git).

Then we need to add `plugin_debugger` to `shared_preload_libraries`

Finally we can create the extension whenever desired.

Could I possibly do this from docker-compose, possibly with a custom Dockerfile? It's only for our testing environments.

I see [something similar here](https://git.treelet.net/suitcase/postgres-docker/blob/master/Dockerfile). I was wondering/hoping if timescale would be interested in making this plugin shipped by default (just not enabled) in their official Docker images.

**Comment by erimatnor** [comment]
Unfortunately, we don't have any current plans to install the debugger by default. But you can always build a custom image based on our Dockerfiles.
