### ISSUE TITLE
Docker installation with volume mapped to windows host machine

### ISSUE THREAD

**Issue by sjjpo2002** [timescale/timescaledb-docker#121]
There is an issue with mapping the data folder to a Windows drive. This is not specific to TimescaleDB and stems from Postgres. See here: https://github.com/docker/for-win/issues/445
The solution they suggested is to modify the docker compose file. But, it seems like Timescale used Docker file and not Docker-compose for building the image and the service. What is the solution for Windows users to install TimescaleDB using Docker and map the data folder to the host machine?

**Comment by k-rus** [comment]
Docker-compose uses docker images. TimescaleDB is provided in a docker image, which can be then used in Docker-compose. TimescaleDB image is based on [PostgreSQL image](https://hub.docker.com/_/postgres), so it should work on Windows in the same way as PostgreSQL docker.

**Comment by svenklemm** [comment]
Closing this since this seems to be an upstream issue.
