### ISSUE TITLE
Add a link to this github repo from the dockerhub readme

### ISSUE THREAD

**Issue by stefanfoulis** [timescale/timescaledb-docker#13]
I needed to do some searching to get here. It would be useful to have a link to this repo from the dockerhub readme at https://hub.docker.com/r/timescale/timescaledb/

Other information like describing the available tags would be useful too (``latest-pg10``, ``latest-pg9.6``, ...).
And a hint to https://hub.docker.com/r/timescale/timescaledb-postgis/

**Comment by RobAtticus** [comment]
Thanks @stefanfoulis, yeah I've been meaning to do some of those things. Just always gets interrupted :) Will hopefully get to it soon

**Comment by RobAtticus** [comment]
I went ahead and updated, let me know if you think of anything else that should be there.

**Comment by stefanfoulis** [comment]
Perfect 🎉
