### ISSUE TITLE
2.1.0

### ISSUE THREAD

**Issue by austinnichols101** [timescale/timescaledb-docker#139]
Add image for timescaledb 2.1.0

Ref: https://github.com/timescale/timescaledb/releases/tag/2.1.0

**Comment by erimatnor** [comment]
It will be updated momentarily. In the meantime, Docker images and other packages (deb, rpm) should already be out.

**Comment by austinnichols101** [comment]
Any idea when the pg13 docker (timescale/timescaledb:2.1.0-pg13) image will be available?  I'm not seeing any pg13 images on https://hub.docker.com/r/timescale/timescaledb/tags?page=1&ordering=last_updated
