### ISSUE TITLE
1.7.5 Not Availble in 2.x.y images

### ISSUE THREAD

**Issue by tylerfontaine** [timescale/timescaledb-docker#142]
The latest 1.x binary availalable in the 2.x packages (2.0.2, 2.1.0, 2.1.1 checked) is 1.7.4. It seems like 1.7.5 got skipped somehow.

It seems likely related to grabbing the older versions from the previous version of the image: https://github.com/timescale/timescaledb-docker/blob/master/Dockerfile#L31-L38

Since 1.7.5 came out after the first 2.x image, it probably never saw it should grab 1.7.5, so it was never included.

**Comment by svenklemm** [comment]
I rebuilt those images and they should all have 1.7.5 now
