### ISSUE TITLE
[Bug] "shared_preload_libraries" in postgresql.conf is missing after restarting the pod

### ISSUE THREAD

**Issue by StefanSa** [timescale/timescaledb-docker#143]
Made a clone from the last git repo and created a new `pg13 bitnami Docker image` with `make image`.

At the initial start of the pod everything is OK:
`shared_preload_libraries = 'pgaudit,timescaledb'` is present  in `postgresql.conf`
However, after a restart, the entry is completely missing, apparently it is then overwritten.

Think that was the same problem:
https://github.com/timescale/timescaledb-docker/issues/127

any help here ?

**Comment by benoist** [comment]
I found that adding this env var worked:
POSTGRESQL_SHARED_PRELOAD_LIBRARIES=timescaledb

**Comment by erimatnor** [comment]
Can you clarify whether this problem was fixed or not in #127?

**Comment by JamesMasonRC** [comment]
Setting the environment variable worked for me. I'm running `timescale/timescaledb:2.5.0-pg13-bitnami`, pulled down a few minutes ago.

**Comment by svenklemm** [comment]
Seems to be fixed so closing. Feel free to reopen if you still experience this with recent versions.
