### ISSUE TITLE
Default Collation does not exist

### ISSUE THREAD

**Issue by JLockerman** [timescale/timescaledb-docker#146]
**Image:** `timescale/timescaledb:latest-pg12`

## Description ##
The default database collation for the docker image is `en_US.UTF-8`, unfortunately, the default Alpine docker images do not actually support this collation, and any attempt to use it will result in an error.

## Reproduction ##
The simplest way to see this issue is to follow these steps:
1. Determine the default collation for the DB
    ```SQL
    postgres=# \l
                                     List of databases
       Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges   
    -----------+----------+----------+------------+------------+-----------------------
     postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
     template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
               |          |          |            |            | postgres=CTc/postgres
     template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
               |          |          |            |            | postgres=CTc/postgres
    (3 rows)
    ```
2. Create a table with a column collated on this default collation
    ```SQL
    CREATE TABLE test (foo text collate "en_US.utf8");
    ```

### Expected Behavior ###

The table-creation should work.

### Actual Behavior ###

The table-creation errors with:
```
ERROR:  collation "en_US.utf8" for encoding "UTF8" does not exist
LINE 1: create table test (foo text collate "en_US.utf8");
```

## In the Wild ##

At least one user has experienced bugs related to this https://github.com/timescale/timescale-analytics/issues/148. Though we may be able to work around that particular bug in the analytics extension, we don't know how many hidden bugs exist due to users having a different default collation than expected.

## Compatibility ##

Note that changing the default collation to actually be UTF-8 may be a breaking change; it depends on how indices interact with this, and what collation is actually being used. It might be safer to change the default collation to match whatever collation is being used in practice.

**Comment by JLockerman** [comment]
Further evidence that this is a misconfiguration issue. If you run 
```SQL
SELECT collname FROM pg_collation WHERE collname ILIKE '%en_US%';
```
On our Alpine-based docker image you get
```
        collname        
------------------------
 en-US-u-va-posix-x-icu
 en-US-x-icu
(2 rows)
```
while if you run it on a more featureful install, like our Debian-based image, or a self-install, you get something like
```
     collname     
------------------
 en_US.UTF-8
 en_US
 en_US.ISO8859-15
 en_US.ISO8859-1
 en_US
 en_US
(6 rows)
```

**Comment by svenklemm** [comment]
I think this is expected since musl libc doesnt really support collations, but we inherit that from the postgres image. If anything you should report this upstream.

**Comment by jflambert** [comment]
This is also affecting me.

I would prefer the default lc_collate/lc_ctype to be C instead of en_US, just like `[timescaledb-docker-ha](https://github.com/timescale/timescaledb-docker-ha)` does.

**Comment by svenklemm** [comment]
Short of switching the underlying linux distribution of that image which would be a disruptive change this property is inherited by the postgres base image we are using here so I think this issue should be reported upstream.
