### ISSUE TITLE
Generate certificate and enable `ssl = on` on initalization

### ISSUE THREAD

**Issue by timoha** [timescale/timescaledb-docker#149]
Was wondering if it'd make sense to add ability to generate a certificate and enable ssl on initialization along with the timescale-db tune and the rest of operations. The certificate would only be using for `require` case in order to encrypt traffic to timescale.

**Comment by svenklemm** [comment]
If you inherit from our image you can add additional custom initialization scripts. See documentation at https://hub.docker.com/_/postgres/
