### ISSUE TITLE
Pushes to master trigger push of latest docker image to repo

### ISSUE THREAD

**Issue by gayyappan** [timescale/timescaledb-docker#150]
Any push to master branch on this repository triggers push of the docker image to timescale repo if there is a push to master.

Modify the scripts so that only push to a special release_branch triggers a push of the docker image.

From docker-image.yml
```
  1 name: Docker Image CI
  2 
  3 on:
  4   push:
  5     branches: [ master, dev-build ]
  6 
  7 env:
  8   ORG: timescale #timescaledev
  9 
 10 jobs:
```
This would involve making some changes to the current Makefile : a) build images with option to push to docker repo b) build images that publish locally or maybe simply verify that the build works.

**Comment by svenklemm** [comment]
Pushes to master no longer trigger docker build
