### ISSUE TITLE
Data directory "/var/lib/postgresql/data" has invalid permissions

### ISSUE THREAD

**Issue by NeroVanbiervliet** [timescale/timescaledb-docker#151]
**Setup**
- Windows server 2019, as well as Windows 10
- Docker Version 3.4.0 (65384)
- `timescale/timescaledb:latest-pg12`

**Bug**
The timescaledb container crashes when trying to run it with `docker run -d --name some-timescaledb -p 5432:5432 -v //D/MARPLE/TIMESCALE:/var/lib/postgresql/data -e POSTGRES_PASSWORD=password timescale/timescaledb:latest-pg12`

**Logs**
```
initdb: removing contents of data directory "/var/lib/postgresql/data"
running bootstrap script ... The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default time zone ... UTC
creating configuration files ... ok

2021-06-23 08:02:59.368 UTC [53] FATAL: data directory "/var/lib/postgresql/data" has invalid permissions
2021-06-23 08:02:59.368 UTC [53] DETAIL: Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
child process exited with exit code 1
```

**Interpretation**
When mounting the same volume `D:\MARPLE\TIMESCALE` in a clean ubuntu container, it has access rights: files and directories can be created from the container. This means the bug is timescale specific, and not an issue with the docker setup. The problem might be caused because inside the timescale container, the user `postgres` is used for the database, instead of `root`.

**Comment by NeroVanbiervliet** [comment]
The problem is rooted in the parent postgres docker image and is documented in [multiple](https://stackoverflow.com/questions/49148754/docker-container-shuts-down-giving-data-directory-has-wrong-ownership-error-wh/55110235#55110235) [places](https://forums.docker.com/t/data-directory-var-lib-postgresql-data-pgdata-has-wrong-ownership/17963/31). The solution that worked so far for us is using a named docker volume:

First create the volume with `docker volume create db_volume`

Then you can use the volume for timescaledb

```yaml
# docker-compose.yml

services:
...
  timescale:
    image: timescale/timescaledb:latest-pg12 
    volumes:
    - db_volume:/var/lib/postgresql/data
    ...
  
volumes:
  db_volume:
    external: true

```

**Comment by MauriceHenriet** [comment]
Hi, I'm trying yout solution : but then... where do I get the database content datas in Windows 10  directories ? which directory of windows 10 ?

Thx

**Comment by josue101grados** [comment]
ty god
