### ISSUE TITLE
image with multi version installed ?

### ISSUE THREAD

**Issue by comicfans** [timescale/timescaledb-docker#160]
Hello, I'd like to try new timescaledb version(1.7 or 2.4) with docker, but my test data(and pg_dump backup) came from 1.5.1, since timescaledb requires backup/restore with same extension version( upgrade extension after data imported), I can't easily import my old version dump into new version docker files, maybe timescaledb docker can provide some image with multi timescaledb version installed, to ease the migration ?

**Comment by erimatnor** [comment]
Multi-node TimescaleDB is the same binaries. So it is already "installed".
