### ISSUE TITLE
Alternative path to /docker-entrypoint-initdb.d for initialization scripts

### ISSUE THREAD

**Issue by kornerc** [timescale/timescaledb-docker#168]
Hello,

in the [docs](https://hub.docker.com/_/postgres/) (section `Initialization scripts`) of the PostgreSQL Docker image it is recommended to put initialization scripts into the folder `/docker-entrypoint-initdb.d`.
However, the TimescaleDB Docker image uses this folder to install the [TimescaleDB extension](https://github.com/timescale/timescaledb-docker/tree/master/docker-entrypoint-initdb.d).

_Is there a recommendation where to put the initialization scripts so that they cannot interfere with the TimescaleDB setup?_

I ran into the problem when I was mounting ( `-v <my-folder>:/docker-entrypoint-initdb.d`) the folder `/docker-entrypoint-initdb.d` to a host folder which contains my initialization sql-scripts.
Due to that the TimescaleDB setup files were removed and the extensions was not installed.
The solution was to create an own image where the relevant files are copied into the folder of the image. 

A colleague of mine ran into a similar issue where his scripts were executed _before_ the TimescaleDB setup files.

Thanks,
Clemens

**Comment by svenklemm** [comment]
If you inherit from our docker image you can use a different entrypoint
