### ISSUE TITLE
Allow to install python packages from environment variables

### ISSUE THREAD

**Issue by agarciagan** [timescale/timescaledb-docker#169]
I want to use some python modules to analyze data within a PLPython function using Pandas, numpy,...
I have tried to install these modules, and the only workaround I have found is to connect as root and install them manually. It would be great if python modules could be added as an environment variables, and the docker image would install them directly.

The commands I run to install the packages are:

```
docker exec -u root -t -i timescale /bin/bash
apt update
apt install python3-dev python3-pip gcc build-essential
pip3 install pandas
```

One the modules are installed, I can used them within my functions

```
create extension plpython3u

 CREATE FUNCTION pymax2 (a integer, b integer, c integer)
    RETURNS integer
AS $$
import pandas
PYTHON CODE
return c
$$ LANGUAGE 'plpython3u';

```

Thanks

**Comment by svenklemm** [comment]
If you need additional things installed in your docker images the canonical way is to inherit from our docker image.
