### ISSUE TITLE
[feature request] Docker image containing toolkit

### ISSUE THREAD

**Issue by pmzajaczkowski** [timescale/timescaledb-docker#171]
Hey, I would like to request for a tag of your Docker image that would point to the TimescaleDB with the toolkit (https://docs.timescale.com/timescaledb/latest/how-to-guides/hyperfunctions/install-toolkit/#installing-toolkit-on-self-hosted-timescaledb) already pre-installed and configured. That would really speed up the process of adoption of the TimescaleDB, as toolkit contains really cool features, which are, unfortunately, hardly available due to missing toolkit.

**Comment by flixman** [comment]
@pmzajaczkowski By any chance have you given it a try? I have started today with pg14, and I am getting quite some trouble if trying to run "cargo pgx init --pg14 pg_config". The tool fails stating that I should use --pg10, but... my pg is 14 :S.

**Comment by svenklemm** [comment]
The timescaledb-ha image has toolkit included:
https://hub.docker.com/r/timescale/timescaledb-ha/tags

**Comment by SharkWipf** [comment]
Unfortunately the timescaledb-docker-ha image only supports a single arch, unlike this image which supports every major arch. timescaledb-docker-ha won't run on anything but amd64, whereas this image even runs on my old Pi2B (armhf) (timescale/timescaledb-docker-ha#259). 
If you're not on a 64-bits x86 machine you're currently out of luck when it comes to TimescaleDB + toolkit (or any other extensions that don't exist in this container).
