### ISSUE TITLE
Unable to use timescaledb-backup

### ISSUE THREAD

**Issue by dktcl** [timescale/timescaledb-docker#175]
Hi,

I've been struggling to find information on using timescaledb-backup within the Docker image.

From the [Dockerfile on this repo](https://github.com/timescale/timescaledb-docker/blob/master/Dockerfile), it seems like `ts-dump` and `ts-restore` should be available. I am using docker image `timescale/timescaledb:latest-pg13`

Any ideas?

Dave

**Comment by svenklemm** [comment]
ts-dump and ts-restore are discontinued. You should use standard postgres tools e.g. pg_dump instead.
