### ISSUE TITLE
Bring back timescaledb-postgis Docker image

### ISSUE THREAD

**Issue by ngosang** [timescale/timescaledb-docker#177]
The [timescaledb-postgis](https://hub.docker.com/r/timescale/timescaledb-postgis/) Docker image is no longer maintained by you but it's quite popular in open-source projects related to home automation and IoT. It has more than 1 million downloads in DockerHub. Some [Home Assistant addons like LTSS](https://community.home-assistant.io/t/custom-component-long-time-state-storage-ltss-utilizing-timescaledb/155047) depends on it.

I'm building my own image but I would like to use your image. There are [several forks of you Docker image](https://hub.docker.com/search?q=timescaledb-postgis&type=image) but the source code is not available and the images are outdated too. I understand that you may not have a financial incentive to maintain the Docker image but it can help increase the user base and avoid unofficial Docker images with bugs or even malware. 

Related #174 #176

**Comment by svenklemm** [comment]
The timescaledb-ha image has postgis included:
https://hub.docker.com/r/timescale/timescaledb-ha

**Comment by ngosang** [comment]
That image is huge and it includes more services that I don't need.
* timescaledb-ha size = 600 MB (compressed)
* timescaledb-postgis size = 100 MB (compressed)

I'm building my own image for now. If anyone else know a better solution or is interested in maintaining the image let me know.

**Comment by ngosang** [comment]
I will maintain my own Docker image => https://hub.docker.com/r/ngosang/timescaledb-postgis

Last build:
* Postgres 16
* TimescaleDB 2.13.0
* PostGIS 3.4.1

**Comment by wibed** [comment]
@ngosang can you share your dockerfile?

your all russian hackers for all i know :)

**Comment by mxfactorial** [comment]
https://github.com/mxfactorial/timescaledb-postgis

[dockerfile](https://github.com/mxfactorial/timescaledb-postgis/blob/main/Dockerfile) @wibed

**Comment by ngosang** [comment]
I updated https://hub.docker.com/r/ngosang/timescaledb-postgis

The version of each software is in the image tag:

`<timescaledb-version>-<postgres-version>-<postgis-version>`

* 2.24.0-pg18-postgis3.6 (latest tag)
* 2.24.0-pg17-postgis3.6
* 2.24.0-pg16-postgis3.6
* 2.24.0-pg15-postgis3.6
