### ISSUE TITLE
TimescaleDB docker image  - Apache 2 Edition mode

### ISSUE THREAD

**Issue by ltsallas** [timescale/timescaledb-docker#178]
Is it possible to set the TimescaleDB container in an "Apache 2" mode, so one can
-  figure out early what functions are available in the Apache 2 version without having to look at the feature comparison chart 
- avoid getting errors late when deploying to in prod environments the Apache version is used
- avoid creating code for functions that are not going to be used with code generation tools on the database

**Comment by svenklemm** [comment]
From the postgres side the same functions are available independant of license. Functions not suitable for current license will throw an error when executed. But you can certainly set timescaledb.license to apache by passing `-c timescaledb.license=apache` to the docker command.
