### ISSUE TITLE
Can't start timescaleDB docker as non-standart user

### ISSUE THREAD

**Issue by AlekseiSaff** [timescale/timescaledb-docker#179]
Hi, 
starting from 2.3.0-pg13 and higher, I'm not able to start TDB as my own user

    user: "4000"
    volumes:
      - /etc/passwd:/etc/passwd:to

In 2.2.1-PG13 - all good
postgres-lightlog_1  | chmod: /var/run/postgresql: Operation not permitted
postgres-lightlog_1  | The files belonging to this database system will be owned by user "lt".
postgres-lightlog_1  | This user must also own the server process.
postgres-lightlog_1  | 
postgres-lightlog_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres-lightlog_1  | The default database encoding has accordingly been set to "UTF8".
postgres-lightlog_1  | The default text search configuration will be set to "english".
postgres-lightlog_1  | 
postgres-lightlog_1  | Data page checksums are disabled.
postgres-lightlog_1  | 
postgres-lightlog_1  | fixing permissions on existing directory /data ... ok
postgres-lightlog_1  | creating subdirectories ... ok
postgres-lightlog_1  | selecting dynamic shared memory implementation ... posix
postgres-lightlog_1  | selecting default max_connections ... 100
postgres-lightlog_1  | selecting default shared_buffers ... 128MB
postgres-lightlog_1  | selecting default time zone ... UTC
postgres-lightlog_1  | creating configuration files ... ok
postgres-lightlog_1  | running bootstrap script ... ok
postgres-lightlog_1  | performing post-bootstrap initialization ... sh: locale: not found
postgres-lightlog_1  | 2022-02-23 12:48:09.843 UTC [22] WARNING:  no usable system locales were found
postgres-lightlog_1  | ok
postgres-lightlog_1  | syncing data to disk ... ok

In 2.3.0 and higher
Attaching to postgres-test_postgres-lightlog_1
postgres-lightlog_1  | chmod: /data: Operation not permitted
postgres-lightlog_1  | chmod: /var/run/postgresql: Operation not permitted
postgres-lightlog_1  | The files belonging to this database system will be owned by user "lt".
postgres-lightlog_1  | This user must also own the server process.
postgres-lightlog_1  | 
postgres-lightlog_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres-lightlog_1  | The default database encoding has accordingly been set to "UTF8".
postgres-lightlog_1  | The default text search configuration will be set to "english".
postgres-lightlog_1  | 
postgres-lightlog_1  | Data page checksums are disabled.
postgres-lightlog_1  | 
postgres-lightlog_1  | fixing permissions on existing directory /data ... initdb: error: could not change permissions of directory "/data": Operation not permitted

**Comment by svenklemm** [comment]
I dont think this is due to a change by us but by upstream. Can you reproduce those failure with the postgres base image. The error seems to happen in initdb stage which we dont change.
