### ISSUE TITLE
timescale/timescaledb:2.6.0-pg13  There are high-risk vulnerabilities, how to upgrade

### ISSUE THREAD

**Issue by fengshunli** [timescale/timescaledb-docker#181]
need to update alpine version to 3.15.3
![image](https://user-images.githubusercontent.com/18587688/160519835-4ab62489-8d26-447b-8d6a-896c969543ac.png)

**Comment by svenklemm** [comment]
This should be fixed with the 2.6.1 release feel free to reopen if not.
