### ISSUE TITLE
postgis image with Postgres14

### ISSUE THREAD

**Issue by canvural** [timescale/timescaledb-docker#182]
Hi,

I see normal `timescaledb` image supports Postgres 14, but there is no image with postgis extension and Postgres 14 (`timescale/timescaledb-postgis:latest-pg14` for example)

Are there any plans to add it? Or was it forgotten maybe?

**Comment by svenklemm** [comment]
The timescaledb-postgis image is discontinued. Please use the timescaledb-ha image if you need postgis.
