### ISSUE TITLE
Timescaledb dockerfile deprecated things

### ISSUE THREAD

**Issue by ifalex** [timescale/timescaledb-docker#183]
In the current Dockerfile from main branch has a repository that was archived by timescale team.
Is about this one: github.com/timescale/timescaledb-backup
Is this the official Dockerfile that you are using for building the docker images from here? https://hub.docker.com/r/timescale/timescaledb
Are those packages used anylonger? I know timescaledb relies as a backup on pgdump as written in the documentation.
Thank you!

**Comment by ifalex** [comment]
The goal here is to have the image with as many vulns as possible.

**Comment by ifalex** [comment]
Also, is this module needed in the docker image? github.com/timescale/timescaledb-parallel-copy

**Comment by svenklemm** [comment]
This reposity contains some of the Dockerfiles for the images found at https://hub.docker.com/r/timescale/timescaledb

**Comment by svenklemm** [comment]
timescaledb-backup has been removed from the docker image
