### ISSUE TITLE
Broken docker image

### ISSUE THREAD

**Issue by itsnotv** [timescale/timescaledb-docker#200]
The following latest images have libssl error at startup.

`timescale/timescaledb:latest-pg14`
`timescale/timescaledb:2.9.0-pg14`

```
timescaledb  | 2022-12-15 18:45:35.806 UTC [22] ERROR:  could not load library "/usr/local/lib/postgresql/timescaledb-2.8.0.so": Error loading shared library libssl.so.1.1: No such file or directory (needed by /usr/local/lib/postgresql/timescaledb-2.8.0.so)
timescaledb  | 2022-12-15 18:45:35.807 UTC [1] LOG:  background worker "TimescaleDB Background Worker Scheduler" (PID 22) exited with exit code 1
```

Downgrading to `timescale/timescaledb:2.8.1-pg14` works.

**Comment by swiffer** [comment]
yep, same here - upgrading the docker container itself worked fine for me but cannot query the server:

SQLSTATE[58P01]: Undefined file: 7 ERROR: could not load library "/usr/local/lib/postgresql/timescaledb-2.6.0.so": Error loading shared library libssl.so.1.1: No such file or directory (needed by /usr/local/lib/postgresql/timescaledb-2.6.0.so)

**Comment by swiffer** [comment]
https://github.com/timescale/timescaledb-docker/commit/786d165c9c16df7527d4554a2e2c58392005b73f

this seems to not work anymore in v2.x era - also the line 31 is missing a -1 near end of the line:

https://github.com/timescale/timescaledb-docker/commit/786d165c9c16df7527d4554a2e2c58392005b73f#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R31

87b2548c48d2:/# ls -la /usr/local/lib/postgresql/timescaledb
timescaledb-2.5.0.so      timescaledb-2.6.1.so      timescaledb-2.8.0.so      timescaledb-tsl-2.5.1.so  timescaledb-tsl-2.7.0.so  timescaledb-tsl-2.8.1.so
timescaledb-2.5.1.so      timescaledb-2.7.0.so      timescaledb-2.8.1.so      timescaledb-tsl-2.5.2.so  timescaledb-tsl-2.7.1.so  timescaledb-tsl-2.9.0.so
timescaledb-2.5.2.so      timescaledb-2.7.1.so      timescaledb-2.9.0.so      timescaledb-tsl-2.6.0.so  timescaledb-tsl-2.7.2.so  timescaledb.so
timescaledb-2.6.0.so      timescaledb-2.7.2.so      timescaledb-tsl-2.5.0.so  timescaledb-tsl-2.6.1.so  timescaledb-tsl-2.8.0.so

**Comment by reinierpost** [comment]
The broken image we have is `latest-pg13` a.k.a. `2.9.0-pg13`. `2.8.1-pg13` is fine.

What does your release process for images look like?

**Comment by etricky** [comment]
I'm also having the same issue with the timescale/timescaledb:latest-pg14 after the latest docker image update.
`2022-12-18 15:47:28.431 UTC [35] ERROR:  could not load library "/usr/local/lib/postgresql/timescaledb-2.5.1.so": Error loading shared library libssl.so.1.1: No such file or directory (needed by /usr/local/lib/postgresql/timescaledb-2.5.1.so)
`

**Comment by cmvarmour** [comment]
same issue

**Comment by Eyald6** [comment]
Also same issue for `latest-pg12`

**Comment by swiffer** [comment]
`latest-pg15` works - however i think PostgreSQL 15 support has been removed from the 2.9.0 Release notes

**Comment by g-langlois** [comment]
I have the same issue with `2.9.0-pg13`. However in my case, it is happening if trying to downgrade to 2.8.1 via `ALTER EXTENSION timescaledb UPDATE TO '2.8.1;`

```
ERROR:  could not load library "/usr/local/lib/postgresql/timescaledb-2.8.1.so": Error loading shared library libssl.so.1.1: No such file or directory (needed by /usr/local/lib/postgresql/timescaledb-2.8.1.so)
```

The image `2.8.1-pg13` is ok.
I can work around it by installing myself the missing library into the container.
`apk add libssl1.1`

**Comment by svenklemm** [comment]
Thank you for the bugreport, the 2.9.0 docker images should be fixed now and allow using previous timescaledb versions.
