### ISSUE TITLE
Docker secrets are they supported in environment variable?

### ISSUE THREAD

**Issue by FireHelmet** [timescale/timescaledb-docker#202]
Hello TimescaleDB team,

I want to secure my docker compose by not exposing the values of POSTGRES_USER and POSTGRES_PASSWORD.
I commonly use Docker secrets with other containers but in case of TimescaleDB, I didn't find a documentation about which environment variable I should use for.

Could you guide me?

Thanks in advance and enjoy the end of the year

**Comment by lkshminarayanan** [comment]
Happy new year @FireHelmet!

TimescaleDB docker image is built on top of Postgres image and you can use all the `*_FILE` environment variables available in the Postgres image with TimescaleDB images as well.

For example, you can project the secret into `/run/secrets/postgres-passwd` file and pass it to the `POSTGRES_PASSWORD_FILE` environment variable :
```
docker run --name timescaledb -e POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd -d timescale/timescaledb-ha:pg14-latest
```

Similarly you can pass `POSTGRES_USER` via `POSTGRES_USER_FILE` as well. 

More information on the postgres arguments is available here - https://hub.docker.com/_/postgres

Please let us know if this solves your issue.

**Comment by FireHelmet** [comment]
Thank you for your quick answer @lkshminarayanan !

Happy new year too ! Best successes in your pro and personal endeavors !

Perfect, it's what I wanted, I close my ticket, so.

Thanks!

**Comment by lkshminarayanan** [comment]
Thank you @FireHelmet!
