### ISSUE TITLE
Generate image for Postgres v16

### ISSUE THREAD

**Issue by emibcn** [timescale/timescaledb-docker#219]
Postgres v16 has been released 🎉 :
https://www.postgresql.org/about/news/postgresql-16-released-2715/

Could you please build and publish a TimescaleDB version for that?

Thanks in advance!

**Comment by emibcn** [comment]
Any news on this?

**Comment by erimatnor** [comment]
TimescaleDB doesn't support PG16 yet, but it is being worked on. The Docker image will be released once the code is ready and released.

**Comment by emibcn** [comment]
Duplicate [#5752](https://github.com/timescale/timescaledb/issues/5752)
