### ISSUE TITLE
Typo regarding Dockerfile command

### ISSUE THREAD

**Issue by akashagarwal7** [timescale/timescaledb-docker#232]
Hi all. I was going through the Dockerfile and noticed an apparent discrepancy in the following line:
https://github.com/timescale/timescaledb-docker/blob/ddd1609e1bb6f0431f04eb3dbc23486c42537cb9/Dockerfile#L25

Shouldn't the `rm -f $(ls -1 $(pg_config --pkglibdir)/timescaledb-*.so...` bit be `rm -f $(ls -1 $(pg_config --pkglibdir)/timescaledb-1*.so...` instead, and hence matching the `if` condition?

**Comment by jnidzwetzki** [comment]
Hello @kashagarwal7,

Thanks for making us aware of this problem. I have opened a PR (https://github.com/timescale/timescaledb-docker/pull/233) that will fix the deletion logic.

**Comment by akashagarwal7** [comment]
@jnidzwetzki I saw the commits. Happy for the issue to be closed. Thanks for the quick turnaround on this :)
