### ISSUE TITLE
2.15.0-pg16-bitnami image missing in hub.docker.com

### ISSUE THREAD

**Issue by anajavi** [timescale/timescaledb-docker#238]
Only 2.15.0-pg16-repmgr-bitnami seems to be available.

From the build logs it seems that the 2.15.0-pg16-bitnami job is pushing image with the name 2.15.0-pg16-repmgr-bitnami:
https://github.com/timescale/timescaledb-docker/actions/runs/9004565643/job/24737843173

**Comment by svenklemm** [comment]
Fixed by https://github.com/timescale/timescaledb-docker/pull/241
