### ISSUE TITLE
Provide a Docker image based upon the Debian image of Postgres

### ISSUE THREAD

**Issue by anothertobi** [timescale/timescaledb-docker#26]
In order to run Postgres on OpenShift the Debian image of Postgres is necessary since it includes the following change: [Implement "nss_wrapper" for Debian variants](https://github.com/docker-library/postgres/pull/448).

The alpine image doesn't provide such capabilities and therefore can't be run in a restricted (e.g OpenShift) environment.

There should be an image for TimescaleDB which is based on the Debian Postgres image (default / non-alpine tag).

**Comment by bittner** [comment]
With 29MB, the [Ubuntu Minimal](https://blog.ubuntu.com/2018/07/09/minimal-ubuntu-released) image should now provide an acceptable footprint, comparable to the Alpine image.

**Comment by cocowalla** [comment]
I'm also interested in a glibc-based distro image, as I have a requirement to use the [plv8](https://github.com/plv8/plv8) extension, which I've spent many fruitless hours trying to build on Alpine!

I've created my own [Dockerfile](https://gist.github.com/cocowalla/cd123d3fafb73c3ac0343a4494ef45b7) which builds TimescaleDB then copies the output to a standard Debian-based Postgres image, but it would be great to have an "official" image.

**Comment by JWGmeligMeyling** [comment]
The error message you'll get on OpenShift is `initdb: could not look up effective user ID 1000040000: user does not exist` and this issue has been reported for the base PostgreSQL container as well in https://github.com/openshift/origin/issues/15600 and https://github.com/docker-library/postgres/issues/359 .

However, I think this repository already provides images based on Debian, namely the [bitnami](https://github.com/timescale/timescaledb-docker/tree/master/bitnami) based images. Deploying [`timescale/timescaledb:latest-pg11-bitnami`](https://hub.docker.com/r/timescale/timescaledb/tags) to OpenShift works fine for me.

Unfortunately the bitnami image for TimeScaleDB doesn't have a version that comes with Postgis, and neither seems to do the base image: https://github.com/bitnami/bitnami-docker-postgresql/issues/85 . So getting Postgis to work on this image will still require some more work.

**Comment by svenklemm** [comment]
You may use the timescaledb-ha image which is based on ubuntu.

**Comment by anthonyorona** [comment]
Consider that the timescaledb-ha image includes a lot of additional tooling not required by most people. Why doesn't TimeScale start with the postgres images and build on them? I run postgresql and timescaledb in containers, but created my own timescaledb image because they are based on different base images (alpine & debian respectively)

**Comment by fztr** [comment]
I also had to create [my own timescaledb image](https://github.com/jobgetapp/images) based on the official postgres Debian image. It's available here: `ghcr.io/jobgetapp/timescale:pg13-latest`

**Comment by balthild** [comment]
Looks like the `*-bitnami` images have not been updated for some time. The latest one is `2.18.0-pg17-bitnami`
