### ISSUE TITLE
timescaledb extension not loaded when Kubernetes pod respawned

### ISSUE THREAD

**Issue by cloud-rocket** [timescale/timescaledb-docker#34]
When pod was moved to a different Kubernetes node (VM). All DB clients started to receive errors:
```
ERROR    Postgres: could not access file "timescaledb-0.12.0": No such file or directory
```

I needed to manually connect to a running container and run `ALTER EXTENSION timescaledb UPDATE;` for each database (as noted in this [post](https://stackoverflow.com/questions/49790930/postgres-error-after-updating-timescaledb-on-ubuntu-file-not-found)).

Am I doing something wrong?

* Timescaledb was installed with official postgres helm chart and with `pg10` image

Thanks,
Meir Tseitlin

**Comment by RobAtticus** [comment]
Hi @cloud-rocket,

This was a problem with older images of TimescaleDB. We didn't include previous versions of TimescaleDB in the image, so if your container re-pulled the image and got a newer version of TimescaleDB you would be in a weird state with a version mismatch.

While newer versions of our images have at least a few previous versions to prevent this, you should make sure to only re-pull images when pinned to a particular version, e.g. `1.0.1-pg10` and not `latest-pg10`.

**Comment by RobAtticus** [comment]
I am going to close this. If you are still experiencing the issue, please re-open.
