### ISSUE TITLE
FATAL:  role "postgres" does not exist

### ISSUE THREAD

**Issue by vgoklani** [timescale/timescaledb-docker#47]
Hey there,

I added this to my docker-compose file:

    timescaledb0:
      restart: always
      image: timescale/timescaledb
      ports:
        - "127.0.0.1:5432:5432"
      volumes:
        - /opt_docker/data/timescaledb0:/var/lib/postgresql/data
      mem_limit: 32768m
      env_file:
        - ./environment
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - TIMESCALEDB_TELEMETRY=off
      container_name: timescaledb0
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 30s
        timeout: 30s
        retries: 5

and I'm seeing this in the logs:

    FATAL:  role "postgres" does not exist

What's the best way to fix this? Thanks!

**Comment by RobAtticus** [comment]
You can change the test command to `pg_isready -U ${POSTGRES_USER}` so it matches whatever you set as your admin user

**Comment by vgoklani** [comment]
so set it to "root"?

**Comment by RobAtticus** [comment]
If you change the line to:
```
test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
```

It should work no matter what the user is set to. Currently the test line assumes a 'postgres' user is added, which is the default, but won't be there if you set `POSTGRES_USER` to something else.

**Comment by erimatnor** [comment]
Closing since fixed was proposed. Please reopen if still an issue.
