### ISSUE TITLE
PgTune is hidden 🐉, no way to control it

### ISSUE THREAD

**Issue by simPod** [timescale/timescaledb-docker#52]
Today our CI pulled new timescaledb docker image because we were missing version constraint in our docker-compose file. Builds started failing because of this pgtune https://github.com/timescale/timescaledb-docker/blob/master/docker-entrypoint-initdb.d/002_timescaledb_tune.sh Timescale container wouldn't start, with OOM error as as reson of failure. Our CI machine is pretty strong but it probably refused to give resources timescaledb container wanted.

IMO having such script there by default is not a good idea, maybe adding env var that enables it could solve it?

We downgraded the image to `1.1.0-pg10` that doesn't contain pgtune.

**Comment by RobAtticus** [comment]
Hi @simPod,

Sorry to hear that. Perhaps our testing on our machines wasn't sufficient. Someone on our side is looking into it to make sure it respects container limits (at least with Kubernetes we found it can mistake the host's resources for the container's, so maybe that is what happened here).

Apologies for the troubles.

**Comment by simPod** [comment]
Cool, let me know, I can test it then on our side. We haven't taken any
measures on CI server so it's easily reproducible.
Thanks!

**Comment by RobAtticus** [comment]
This issue should address it:
https://github.com/timescale/timescaledb-docker/pull/53

**Comment by RobAtticus** [comment]
Hey @simPod , #53 was merged and new images built. It will try to determine resource limits if it can, so if you can try it out that'd be great. It also has an option to disable timescaledb-tune altogether if it is just not working out, but if you do find issues let us know!

**Comment by simPod** [comment]
@RobAtticus Hi, tried `1.2.1-pg10-oss` and it had no problem anymore. Thanks!
