### ISSUE TITLE
Running Timescale in Kubernetes: Pod recreate results in data loss

### ISSUE THREAD

**Issue by raghavan20** [timescale/timescaledb-docker#68]
Reference: https://stackoverflow.com/questions/57140161/kubernetes-timescaledb-statefulset-changes-lost-on-pod-recreation

I use Kubernetes statefulset to run Timescale. I use Postgres 9.6. When the pod is recreated, it appears to lose DB(s) and underlying tables. The `/var/lib/postgresql` is backed by a persistent volume in Kubernetes.

1. The three entry point files if they are run more than once, will it result in recreation of folder `/var/lib/postgresql/data`? https://github.com/timescale/timescaledb-docker/tree/master/docker-entrypoint-initdb.d
2. How does Timescale know that it has already initialised so that it would not reinitialise databases?
3. Or is there something in Postgres base Docker image that causes to reinitialise its `data` dir?

By reinitialise, I mean it only has DBs (postgres, template0 and template1).

I have raised the question in StackOverflow. Currently the suspicion is TimeScale is reinitialising. Any pointers are appreciated.

**Comment by RobAtticus** [comment]
We have done testing with TimescaleDB in k8s and have not seen the issue you're having. 

1. Nothing in these entry point files creates any databases or removes any. The first adds the extension to template dbs (from which others are made) and the database associated with the PG user. The second updates the pg_hba file to make it a bit more secure. The third runs tuning.
2. TimescaleDB only does initializing when its been created or altered via CREATE EXTENSION and ALTER EXTENSION.
3. I don't think so

Are you sure your StatefulSet is correctly set up and not accidentally being lost when a Pod is taken down? Basically the Docker image just uses whatever data is stored in the PGDATA directory, so it won't re-init if there are things there. It sounds like its not bringing back the same data when the Pod is back online, so either its getting a different volume or the volume has been wiped.

**Comment by raghavan20** [comment]
Thanks for replying.

The problem was there was a VOLUME declaration for `/var/lib/postgresql/data` in `postgres:9.6` Dockerfile which caused additional mount on the container. That mount `/var/lib/postgresql/data` was ephemeral when we had the volume mount at `/var/lib/postgresql`. But we were not able to mount AKS volume to `/var/lib/postgresql/data` because the volume came with `lost+found` subdirectory and Postgres expects empty directory to store DB files. 

The fix was to mount volume at `/var/lib/postgresql/data` and tell Postgres to use a subdirectory underneath `/var/lib/postgresql/data` to store files with `PGDATA` env var.

Below are the relevant parts of fix in the k8s statefulset configuration

```
env:
- name: PGDATA
  value: "/var/lib/postgresql/data/dbfiles"        
...
volumeMounts:
- mountPath: /var/lib/postgresql/data
  name: timescaledata
```
