### ISSUE TITLE
Upgrade PG to 11.5 to fix Grafana provisioning

### ISSUE THREAD

**Issue by thirstyfish** [timescale/timescaledb-docker#69]
Could you please release a new version with PG 11.5 as it's not possible to auto provision Grafana with a Postgres backend on PG 11.4 due to this issue:
https://github.com/grafana/grafana/issues/17771#issuecomment-519549120
This is fixed by PG 11.5

Cheers!

**Comment by RobAtticus** [comment]
Hey @thirstyfish , thanks for bringing this to our attention. I will put it on my plate.

**Comment by RobAtticus** [comment]
@thirstyfish should be updated now

**Comment by thirstyfish** [comment]
Thanks mate! Just tested it and now the Grafana auto provisioning works as well. Cheers!
