### ISSUE TITLE
1.4.2-pg11-bitnami image is missing on docker hub

### ISSUE THREAD

**Issue by mwalser** [timescale/timescaledb-docker#72]
Hello,

it seems like the 1.4.2-pg11-bitnami image is missing on docker hub even though TimescaleDB 1.4.2 was released two weeks ago. This is quite unfortunate for us since we're experiencing timescale/timescaledb#1397 which is fixed in 1.4.2.

Is that intentional or was it simply forgotten to publish the image?

**Comment by bboule** [comment]
hey @mwalser this has been fixed apologies for any confusion please let us know if you have any other issues

**Comment by mwalser** [comment]
Hi @bboule, thank you for the fast response! I was able to successfully pull and run the image.
