### ISSUE TITLE
Provide a timescaledb-postgis-bitnami release

### ISSUE THREAD

**Issue by jwgmeligmeyling** [timescale/timescaledb-docker#73]
The bitnami releases are essential for running TimescaleDB on Kubernetes/OpenShift, but a version that includes Postgis does not exist. 

See also: https://github.com/timescale/timescaledb-docker/issues/26#issuecomment-521819393

**Comment by djbrown** [comment]
What's about https://hub.docker.com/r/timescale/timescaledb-postgis/?

**Comment by svenklemm** [comment]
If you need postgis you may use the timescaledb-ha image
