### ISSUE TITLE
PostGIS - could not find libproj

### ISSUE THREAD

**Issue by tomansill** [timescale/timescaledb-docker#75]
Hi all, 

I am trying to build a Docker image of TimescaleDB with PostGIS extension. I've pulled down the project at `master` branch and cd into `postgis` directory, then called `make`. It was able to install dependencies, download PostGIS source code, but it has stopped at `configure` command where it said 
```
configure:  error: could not find libproj - you may need to specify the directory of a PROJ.4 installation using --with-projdir
```

I also see an error message previous the libproj error but I don't know if it's relevant to the error that I'm having

```
checking for shared library run path origin... /bin/sh: can't open 'build-aux/config.rpath': No such file or directory
done
```

I have verified that `proj` and `proj-dev` are installed in the image prior running `configure` script. I have no idea where exactly `proj` files are installed in. Should I try look for them then use `--with-projdir` command?

**Comment by dsschneidermann** [comment]
Have the same here and it's not a solution to specify a `--with-projdir` option. There is an issue with libproj 15.2 that I don't have a clue how to resolve.

```
bash-5.0# ldd /usr/lib/libproj.so.15.2.0 
        /lib/ld-musl-x86_64.so.1 (0x7f7d5b9b3000)
        libsqlite3.so.0 => /usr/lib/libsqlite3.so.0 (0x7f7d5b6b8000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f7d5b563000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f7d5b9b3000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f7d5b54f000)
Error relocating /usr/lib/libproj.so.15.2.0: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
```

When using the timescale/timescaledb-postgis image:
```
bash-5.0# ldd /usr/lib/libproj.so.15.1.0
        /lib/ld-musl-x86_64.so.1 (0x7f8f019de000)
        libsqlite3.so.0 => /usr/lib/libsqlite3.so.0 (0x7f8f0170d000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f8f015b8000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f8f019de000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f8f015a4000)
```

**Comment by tomansill** [comment]
It seems to me that the current PostGIS source files depends upon older version of Proj 4. And Alpine Linux only has the most latest one available 6.2.0. I believe they may have deleted proj4 from their mirrors.

So, I think someone needs to either build or obtain an APKBUILD of proj4 and install proj4. Then they may attempt to install PostGIS.

OR we wait for PostGIS to update their build dependency to use Proj 6

**Comment by tomansill** [comment]
Related: https://gitlab.alpinelinux.org/alpine/aports/issues/10612

**Comment by erimatnor** [comment]
@tomansill Closing this issue since it is unclear that this is an issue related to our Docker images. Please reopen if you have a specific suggestion on enhancement or feature request.
