### ISSUE TITLE
Question: locale support

### ISSUE THREAD

**Issue by tmtron** [timescale/timescaledb-docker#78]
How can we set a default locale for new database instances?

The current docker image (`timescale/timescaledb:1.5.0-pg11`) is based on `postgres-alpine` so the usual way of setting the locale/collation/etc. does not work: e.g. for initdb: `POSTGRES_INITDB_ARGS=--lc-collate=de-AT --lc-ctype=de-AT`  
see this [issue on stackexchange](https://dba.stackexchange.com/q/252482/164398)

So how can we resolve this?  

-  do you provide an image that is based on the default postgres image (i.e. not -alpine)?  
  I guess not yet, because of #26
- or is there a simple way to activate/install locales in the current alpine image?

**Comment by erimatnor** [comment]
You can build your own image that extends the base one that includes the locales you need. You can also use a Debian based image; for example, I believe `timescale/timescaledb-ha` is Debian-based.
