### ISSUE TITLE
Missing environment variables

### ISSUE THREAD

**Issue by galvez** [timescale/timescaledb-docker#8]
`POSTGRES_PASSWORD` doesn't seem to do a thing here. I looked it up and it looks like you guys are replacing the ENTRYPOINT with your own without fully running this guy right here:

https://github.com/docker-library/postgres/blob/master/9.6/docker-entrypoint.sh

The consequence is that users of this image are required to set up authentication manually.

**Comment by RobAtticus** [comment]
Are you sure? I just ran it with:
`docker run -e POSTGRES_PASSWORD=foo -p 5432:5432 timescale/timescaledb:latest`

When I tried to connect with psql:
```
$ psql -U postgres -h localhost
Password for user postgres:
```

Entering 'foo' worked. We do call `docker-entrypoint.sh` at the end of `backup_init.sh` (https://github.com/timescale/timescaledb-docker/blob/master/backup_init.sh)

**Comment by galvez** [comment]
@RobAtticus My apologies, I must have gotten something wrong! Will double check.

**Comment by RobAtticus** [comment]
No worries! If it still doesn't work for you, please re-open and we can investigate further :)
