### ISSUE TITLE
Latest postgis release on dockerhub is 1.4.2

### ISSUE THREAD

**Issue by TheEggi** [timescale/timescaledb-docker#83]
It seems that https://hub.docker.com/r/timescale/timescaledb-postgis does not contain the latest version.

**Comment by amincheloh** [comment]
any updates? @bboule @erimatnor

**Comment by jflambert** [comment]
Please update

**Comment by RobAtticus** [comment]
@jflambert @amincheloh and @TheEggi , I have pushed new images for postgis based on Timescaledb 1.6.0, and we should have timely releases going forward with this PR: #84

**Comment by jflambert** [comment]
@RobAtticus  I think you can close this by now ;)

**Comment by jflambert** [comment]
Hi @RobAtticus  and @k-rus I noticed that the postgis image is still stuck at 2.3.0 instead of 2.3.1

https://hub.docker.com/r/timescale/timescaledb-postgis/tags?page=1&ordering=last_updated&name=2.3.1

**Comment by k-rus** [comment]
> Hi @RobAtticus and @k-rus I noticed that the postgis image is still stuck at 2.3.0 instead of 2.3.1
> 
> https://hub.docker.com/r/timescale/timescaledb-postgis/tags?page=1&ordering=last_updated&name=2.3.1

cc @erimatnor @mkindahl
