### ISSUE TITLE
Latest update killed my postgres

### ISSUE THREAD

**Issue by flashspys** [timescale/timescaledb-docker#85]
Hello there. After the update to the latest docker image (3 hours ago) my postgres is not working anymore. I'm using the 'timescale/timescaledb-postgis:latest-pg11' tag. You updated the postgis version from 2.5 to 3.0, **without providing an update path**. So every statement to a table with the enabled postgis extension fails with 
```
ERROR:  could not access file "$libdir/postgis-2.5": No such file or directory
```
because the 2.5 is not installed anymore and the updater only works if 2.5 is installed.

**Comment by RobAtticus** [comment]
Hi @flashspys , did not realize I had made that change. I am replacing the images on Docker with one that uses 2.5.3 so it should be available in just a few mins.

**Comment by flashspys** [comment]
DB is up again, thank you very much!

**Comment by flashspys** [comment]
You should maybe consider to put the postgis version into the tags. Thanks for the quick support.

**Comment by RobAtticus** [comment]
Thanks, we'll look for a way to improve it!
