### ISSUE TITLE
Bumping from 1.6.0-pg11 to 1.6.1-pg11 deprecated postgres superuser password env var

### ISSUE THREAD

**Issue by BeyondEvil** [timescale/timescaledb-docker#89]
In the `1.6.0-pg11` docker image the environment variable for the postgres superuser password was `PGPASSWORD`.

In `1.6.1-pg11` this was changed to `POSTGRES_PASSWORD`.

**Comment by k-rus** [comment]
@BeyondEvil 
TimescaleDB image is built from [postgres](https://hub.docker.com/_/postgres) docker image, which is supposed to supply environment variable `POSTGRES_PASSWORD`. `1.6.0` and `1.6.1` are different versions of TimescaleDB, where no breaking changes introduced to the product. Images for `1.6.0` and `1.6.1` use latest version of PG11 at the time they are built, so you are likely to observe the behaviour related to this difference.
It is common to use product version in the tags and to not have docker image specific tag.

Can you improve the issue message to describe the problem, so it can be useful for other users?

I looked into PG image and it requires `POSTGRES_PASSWORD` to use and some fix was done related to this recently, but I am still unsure why it was possible to use `PGPASSWORD` in `1.6.0`.

**Comment by k-rus** [comment]
@BeyondEvil 
Can you remember if you did something specific to use `PGPASSWORD` when you started to use `1.6.0` image? Entrypoint of postgres docker image sets `PGPASSWORD=POSTGRES_PASSWORD`. Postgres still uses `PGPASSWORD` and I guess in certain type of connections it can be reset and used directly.

**Comment by BeyondEvil** [comment]
Not that I can see. It wasn't me who originally set it up.

Our config in Circle CI had this:

```yml
    docker:
      - image: timescale/timescaledb:latest-pg11
        environment:
          PGPASSWORD: testthecode
```

And from one day to another started failing with:

```bash
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD to a non-empty value for the
       superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".

       You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
       connections without a password. This is *not* recommended.

       See PostgreSQL documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html
```

After some troubleshooting I noticed that timescaledb image had seen a new release. Pinning the version to 1.6.0 fixed the issue.

Yes, using "latest" in any form is bad practice.

Later I pinned the version to 1.6.1 and changed the `ENVIRONMENT` key to `POSTGRES_PASSWORD`.

**Comment by k-rus** [comment]
Thank you for clarifying and providing details! I think it is enough details for us to look into the issue and try to understand what happened.

**Comment by k-rus** [comment]
@BeyondEvil I believe you were hit by the change in PG docker image, which introduces stricter securing: https://github.com/docker-library/postgres/issues/681
Internally we are discussing to introduce tags with the exact version of PG used, however it will not help with latest tag.

**Comment by BeyondEvil** [comment]
> @BeyondEvil I believe you were hit by the change in PG docker image, which introduces stricter securing: [docker-library/postgres#681](https://github.com/docker-library/postgres/issues/681)
> Internally we are discussing to introduce tags with the exact version of PG used, however it will not help with latest tag.

Exact version of PG would be good.

Yeah, hence why using "latest", in any form, in production is a _bad_ idea. But that's our own fault, not yours. :)

**Comment by k-rus** [comment]
Basically, all newly created PG docker images are affected by the change in the docker-library for PG, which requires to either set the password using `POSTGRES_PASSWORD` or use `POSTGRES_HOST_AUTH_METHOD=trust`. Since PG is under the hood of TSDB images, it affects TSDB images, which use new images of PG.

**Comment by svenklemm** [comment]
closing this since those versions are very old and no longer supported
