### ISSUE TITLE
timescale/timescaledb-postgis compatible with ARM

### ISSUE THREAD

**Issue by androidand** [timescale/timescaledb-docker#97]
Please update the docker script so that you can generate an image of 
timescale/timescaledb-postgis
compatible which is compatible with ARM / ARM 64 just like
timescale/timescaledb
is.

Background:

Trying to run timescale/timescaledb-postgis fails with this error on a 32 bit os running on a Raspberry Pi 4:

standard_init_linux.go:211: exec user process caused "exec format error"

A lot of people elaborate with IoT and docker on Raspberry Pis. There's an interest in time series databases in the community for Home Assistant, an open source home automation platform. Offering a simple way of running TimescaleDB together with Home Assistant would be beneficial for everyone involved.

**Comment by huonw** [comment]
I did some brief investigation for this in https://github.com/timescale/timescaledb-docker/issues/25#issuecomment-749917592 (it's not immediately trivial, in that building the Dockerfile on ARMv7 doesn't work). @dekiesel [pointed out](https://github.com/timescale/timescaledb-docker/issues/25#issuecomment-750062483) the https://github.com/dekiesel/arm7v32_timescaledb image they've created.

**Comment by nicolavs** [comment]
community built image 
https://hub.docker.com/r/thobi85/timescale-postgis from

**Comment by svenklemm** [comment]
closing this since we don't provide timescaledb-postgis anymore
