### ISSUE TITLE
container_linux.go:344: starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown.

### ISSUE THREAD

**Issue by Nicolai6120** [timescale/timescaledb-docker#98]
I`m trying to execute docker command from official timescale docs:

`docker run -d --name timescaledb -p 5432:5432 -e POSTGRES_PASSWORD=password timescale/timescaledb:latest-pg12`

and I`m getting this one error:

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown.`

**Comment by Nicolai6120** [comment]
![image](https://user-images.githubusercontent.com/6821061/81933552-488e4c00-95f6-11ea-9db4-ad2b1c9781f1.png)

**Comment by Nicolai6120** [comment]
UPD: looks like permission problem on file docker-entrypoint.sh of underlying postgres image.

But there is no problem with another image:

docker run -d --name timescaledb -p 5432 :5432 -e POSTGRES_PASSWORD=password timescale/timescaledb

And now everithing is good. So what difference between timescale/timescaledb:latest-pg12 (or timescale/timescaledb:latest-pg11) and timescale/timescaledb images?

**Comment by svenklemm** [comment]
Closing because this is old ticket.
