### ISSUE TITLE
Compatibility with Dokku postgres plugin

### ISSUE THREAD

**Issue by AxelTheGerman** [timescale/timescaledb-docker#99]
Hi,
I am just starting to use TimescaleDB and ran into an issue for my deployment right away. Thanks for providing a docker image based on the official Postgres one!

I'm using dokku (similar to Heroku) to deploy my apps and they support Postgres with a nice plugin. The plugin even allows to specify the image name and version which lets you install TimescaleDB directly!

However, bad news: it doesn't start the container correctly :disappointed:
Good news though is that all it takes is to copy existing `server.crt` and `server.key` from a different Postgres DB container to the TimescaleDB one.

This issue and solution was brought up here https://github.com/dokku/dokku-postgres/issues/153 - I was wondering if that's maybe something that can be fixed in the `timescaledb` docker image.

**Is there a specific reason why TimescaleDB deletes the server certificate?** - can we simply not delete it or maybe generate one?

**Comment by jonathan-s** [comment]
Out of curiosity, from where to where do you need to copy this. Ie what is the path?

**Comment by bfontaine** [comment]
@jonathan-s A bit late, but it’s probably the path given here: https://github.com/dokku/dokku-postgres/issues/153#issuecomment-595390537

**Comment by svenklemm** [comment]
Hmm closing this since we don't delete any certs.

**Comment by nileio** [comment]
actually the issue still exists.. why the `server.crt` and `server.key` does not exist in your image

**Comment by AxelTheGerman** [comment]
I assume they're not deleted but either not generated or not copied (just my educated guess)

**Comment by svenklemm** [comment]
The standard postgres image does not have certs either so there probably is a hook which adds them which doesnt get triggered in the timescaledb image but that seems more like an issue with the hook.
